### ISSUE TITLE
respond-to: no-query fails at base level

### ISSUE THREAD

**Issue by jakob-e** [at-import/breakpoint#114]
Attempting to use respond-to and no-query at base-level throws 
"Base-level rules cannot contain the parent-selector-referencing character '&'."

````SCSS
// Tested on Sassmeister.com
// SCSS       (3.3.14)
// Breakpoint (v2.4.2)

@import "breakpoint";
$breakpoint-no-query-fallbacks: true;
$breakpoints: add-breakpoint('mobile',(0px 480px, 'no-query' '.no-mq-mobile'));

// Works
.wrapper {
  @include respond-to(mobile){
    .selector { content:'Works because of wrapper ; }
  }
}

// Fails
@include respond-to(mobile){
  .selector { content:'Breaks at base-level' ; }
}
````

__PS__. why not omit zero values and cut CSS bloat?
@media (min-width: 0px) and (max-width: 480px) {  }  should be @media (max-width: 480px) {  }
