### ISSUE TITLE
No query fallback doesn't seem to work with libsass 3.1

### ISSUE THREAD

**Issue by ksubileau** [at-import/breakpoint#134]
Hello,
I'm trying to use the latest revision of breakpoint available on this repo (@da1ffe9) with the stack gulp-sass 1.3.3 / node-sass 2.1.1 / libsass 3.1.0. I would like to support browsers without media-queries, so I tried to set up the no query fallback.

But the fallback is missing in the compiled CSS if I compile with this stack. However, the same scss input give the right result with the original sass compiler (3.4.6).

Here is an example:
```scss
@import "breakpoint";

$bp: 680px, 'no-query' '.no-mq';
@include bkpt-set('no queries', false);
@include bkpt-set('no query fallbacks', true);
body {
    background-color: black;
    @include breakpoint($bp) {
        background-color: red;
    }
}
```

Expected output (compiled with Sass compiler v3.4.6):
```css
body {
  background-color: black; }
  @media (min-width: 680px) {
    body {
      background-color: red; } }
  .no-mq body {
    background-color: red; }
```

Actual output with libsass 3.1.0:
```css
body {
  background-color: black; }
  @media  (min-width: 680px) {
    body {
      background-color: red; } }
   /* .no-mq body is missing !! */
```
