### ISSUE TITLE
Ability to use variables specific to breakpoints

### ISSUE THREAD

**Issue by luksak** [at-import/breakpoint#24]
I would like to be able to do something like this:

``` SCSS

// Define global variable for breakpoint
@include breakpoint(720px) {
  $width:  720px;
}

// And then use it somewhere else
@include breakpoint(720px) {
  width:  $width;
}
```

To me this seems to be critical to be able to integrate other tools like Zen Grids where I am currently trying to do something like this:

``` SCSS
@include breakpoint($bp-1) {
  $zen-column-count:  6;
  $zen-grid-width:    240px;
}

@include breakpoint($bp-1) {
  #page-wrapper {
    width: $zen-grid-width;

     > .panel-main_content {
      @include zen-grid-container();
      @include zen-grid-item-base();
    }
  }
}
```

Or am I missing something? Is it possible somehow?
