### ISSUE TITLE
Multiple breakpoints not in a single variable cause an error

### ISSUE THREAD

**Issue by robwierzbowski** [at-import/breakpoint#33]
This works:

``` scss
$thisbkpt: 500px, min-height 200px;
@include breakpoint($thisbkpt) {...}
```

But, 

``` scss
$thisbkpt: 500px;
@include breakpoint($thisbkpt, min-height 200px) {...}
```

and 

``` scss
@include breakpoint(500px, min-height 200px) {...}
```

fail with the error 

> Invalid CSS after "min-height ": expected media query list, was "200px and (min-...".
