### ISSUE TITLE
$breakpoint-no-queries inconsistencies

### ISSUE THREAD

**Issue by ethanmuller** [at-import/breakpoint#44]
I'm getting some inconsistent behavior between versions 1.3 and 2.0.2 when using the `$breakpoint-no-queries` option.

When `$breakpoint-no-queries` is true, and when I pass `$no-query: true` to the mixin, I expect it to strip out media queries and apply their contents. This happens in 1.3, but not in 2.0.2. In other words, `$no-query` makes no difference to 2.0.2.

For example, here is what I get when using the "No Wrapping Selector, Separate Stylesheet" example from the current docs

Input:

**style.scss**

``` scss
$breakpoint-no-queries: false;

@import 'layout';
```

**no-mq.scss**

``` scss
$breakpoint-no-queries: true;

@import 'layout';
```

**_layout.scss**

``` scss
@import 'compass';
@import 'breakpoint';

#foo {
  background: red;
  @include breakpoint(567px, $no-query: true) {
    background: green;
  }
}
```

Output:

**style.css** _(same for 1.3 and 2.0.2)_

``` css
#foo {
  background: red;
}
@media (min-width: 567px) {
  #foo {
    background: green;
  }
}
```

**no-mq.css** _(2.0.2)_

``` css
#foo {
  background: red;
}
```

**no-mq.css** _(1.3)_

``` css
#foo {
  background: red;
  background: green;
}
```

If I understand correctly, 1.3's behavior is the intended way for this feature to work.
