### ISSUE TITLE
Allow nesting of media queries, magically.

### ISSUE THREAD

**Issue by iamcarrico** [at-import/breakpoint#51]
So, Sass allows you to write this:

``` sass
@media (min-width: 500px) {
  -foo: bar;

  @media (max-width: 899px) {
     -baz: stuff;
  }
}
```

and it will print out like so:

``` css
@media (min-width: 500px) {
  -foo: bar;
}

@media (min-width: 500px) and (max-width: 899px) {
  -baz: stuff;
}

```

Why dont we allow breakpoint to do this?

``` sass
$small: 500px;
$large: 900px;

@include breakpoint($small) {
  -foo: bar;

  @include breakpoint($large - 1) {
    -baz: stuff;
  }
}
```

to do the same. OR better yet:

``` sass
$small: 500px;
$large: 900px;

@include breakpoint($small) {
  -foo: bar;

  @include breakpoint($large) {
    -baz: stuff;
  }
}
```

and have breakpoint (in a setting to change this behavior), automatically remove one pixel so bad things dont happen. Related: will bad things happen if we are using em's if so how do we protect? 

(This is half an issue to talk features, half so I remember to do it...)
