### ISSUE TITLE
Fenced Queries Misparsed When Combined with Media Type

### ISSUE THREAD

**Issue by Snugug** [at-import/breakpoint#64]
When using a fenced media query with shorthand syntax as well as a media type, two min-width queries get created instead of a min-width and a max-width query. Example:

``` scss
@import "breakpoint";

$fenced: handheld 600px 980px;

.foo {
    width: 100%;
    @include breakpoint($fenced) {
        width: 20px;
    }
}
```

``` css
.foo {
  width: 100%;
}
@media handheld and (min-width: 600px) and (min-width: 980px) {
  .foo {
    width: 20px;
  }
}
```
