### ISSUE TITLE
not/only media produces errors

### ISSUE THREAD

**Issue by Snugug** [at-import/breakpoint#65]
When using not/only with a media type, the media stuff gets mis-parsed. For not, we get `(min-width: false)`, with only we get a `(media: only)` query. This happens with compound queries as well. When combining a not media with a fenced query, we get a fatal error. Example:
### Only

``` scss
@import "breakpoint";

$fenced: only print;

.foo {
    width: 100%;
    @include breakpoint($fenced) {
        width: 20px;
    }
}
```

``` css
.foo {
  width: 100%;
}
@media (print: only) {
  .foo {
    width: 20px;
  }
}
```
### Not

``` scss
@import "breakpoint";

$fenced: not print;

.foo {
    width: 100%;
    @include breakpoint($fenced) {
        width: 20px;
    }
}
```

``` css
.foo {
  width: 100%;
}
@media (min-width: false) {
  .foo {
    width: 20px;
  }
}
```
### Not with Fenced Query

``` scss
@import "breakpoint";

$fenced: not print 600px 900px;

.foo {
    width: 100%;
    @include breakpoint($fenced) {
        width: 20px;
    }
}
```

``` css
false is not a number for `min'
```
