### ISSUE TITLE
Change in no-query on upgrade

### ISSUE THREAD

**Issue by gmclelland** [at-import/breakpoint#84]
I just upgraded to the latest release, but I can't seem to figure out how to change my breakpoint calls.
I was previously using code like:

``` scss

$medium: 47.75em;

// Give the inside pages a different background
.not-front .l-root-header{
  background:transparent image-url('white-fade-repeating.png') 0 0 repeat-x;

  @include breakpoint($medium, $no-query: '.lt-ie9') {
    background:$color-light-tan image-url('white-fade.png') repeat-x bottom;
  }
}
```

How can I translate that into the new syntax?  I was wanting this code to print something like this all in the same file:

``` css
.not-front .l-root-header{
  styles...
}

.lt-ie9 .not-front .l-root-header{
  styles...
}
```

Sorry, I couldn't fully understand the documentation on the wiki
